package:
  name: cmder-git
  version: 1.1.3

source:
  fn: cmder.7z [win]
  url: https://github.com/bliker/cmder/releases/download/v1.1.3/cmder.7z [win]

requirements:
  build:
    - 7za

build:
  number: 0

about:
  home: http://bliker.github.io/cmder/
  license: MIT

# vim:set ts=8 sw=2 sts=2 tw=78 et:
