package:
  name: qt5
  version: 5.9.1

source:
  fn:   qt-everywhere-opensource-src-5.9.1.tar.xz
  url:  http://download.qt.io/official_releases/qt/5.9/5.9.1/single/qt-everywhere-opensource-src-5.9.1.tar.xz
  md5:  77b4af61c49a09833d4df824c806acaf

build:
  detect_binary_files_with_prefix: true

requirements:
  build:
    - icu           
    - python
    - libpng        
    - jpeg                        [unix]
    - zlib                        [unix]
    - xz                          [unix]
    - bison                       [linux]
    - flex                        [linux]
    - fontconfig                  [linux]
    - gst-plugins-base 
    - libxcb                      [linux]
    - gcc                         [linux]
    - freetype                    [linux]
    - openssl                     [linux]

  run:
    - icu          
    - zlib                        [unix]
    - libpng        
    - jpeg                        [unix]
    - fontconfig                  [linux]
    - gst-plugins-base   
    - libxcb                      [linux]
    - libgcc                      [linux]
    - freetype                    [linux]
    - openssl                     [linux]
    - xz

about:
    home: http://www.qt.io
    license: LGPL
