package:
  name: nettle
  version: 2.7.1

source:
  fn: nettle-2.7.1.tar.gz
  url: http://www.lysator.liu.se/~nisse/archive/nettle-2.7.1.tar.gz

about:
  home: http://www.lysator.liu.se/~nisse/nettle/
  license: GPL
