package:
  name: hunspell-en
  version: 2014.02.10

source:
  url: http://extensions.openoffice.org/en/download/17707
  fn: dict-en.oxt

requirements:
  run:
    - hunspell

test:
  commands:
    - echo 'test' | hunspell
    - echo 'mispellled' | hunspell

about:
  home: http://extensions.openoffice.org/en/project/english-dictionaries-apache-openoffice
  summary: "English spelling dictionaries for hunspell. Includes en_AU (Australian), en_CA (Canadian), en_GB (British), en_US (American), and en_ZA (South African)"
  license: GPL
