package:
  name: msmtp
  version: 1.4.32

source:
  fn: msmtp-rel-1-4-32.zip [osx]
  url: https://github.com/tpn/msmtp/archive/rel-1-4-32.zip [osx]
  fn: msmtp-1.4.32.tar.gz [linux]
  url: http://downloads.sourceforge.net/project/msmtp/msmtp/1.4.32/msmtp-1.4.32.tar.bz2 [linux]

build:
  number: 0

requirements:
  build:
    - openssl
    - autoconf [not linux]
    - automake [not linux]
    - gettext
    - pkg-config [not linux]
  run:
    - openssl
    - gettext

test:
  commands:
    - msmtp --help

about:
  home: http://msmtp.sourceforge.net/
  license: GPL 3

# vim:set ts=8 sw=2 sts=2 tw=78 et:
