package:
  name: vagrant
  version: 1.5.3

source:
  url: https://dl.bintray.com/mitchellh/vagrant/vagrant_1.5.3.dmg
  fn: vagrant_1.5.3.dmg
  sha1: ae964b580bc6a56c60a220b567c3261904ca2559
#  sha256: 7bb8a7cc1246bbb5831e78b31f0335777bcd9d16bc88016430a054dd2f2e038c

test:
  files:
    - Vagrantfile
  commands:
    - vagrant up
    - vagrant ssh -c "echo test"
    - vagrant destroy -f

about:
  home: http://www.vagrantup.com/
  license: MIT
