package:
  name: aspell
  version: 0.60.7.20110707

source:
  fn: aspell-0.60.7-20110707.tar.gz
  url: ftp://alpha.gnu.org/gnu/aspell/aspell-0.60.7-20110707.tar.gz
  sha1: fcd3430a03fcda27d7359d6bbbc3c1396438c183
  patches:
    # http://www.freebsd.org/cgi/query-pr.cgi?pr=180565&cat=
    - aspell.patch


build:
  number: 5

test:
  commands:
    - aspell --help
    # Make sure the build prefix is not hard-coded into aspell
    - if aspell dump config | grep "_build"; then exit 1; fi

about:
  home: http://aspell.net/
  license: LGPL
  summary: GNU Aspell is a Free and Open Source spell checker designed to eventually replace Ispell.
