package:
  name: aspell-en
  version: 7.1.0

source:
  fn: aspell6-en-7.1-0.tar.bz2
  url: ftp://ftp.gnu.org/gnu/aspell/dict/en/aspell6-en-7.1-0.tar.bz2
  sha1: d45ccda0c03e2a679c2936487ec851a1896b8150

requirements:
  build:
    - aspell
  run:
    - aspell

test:
  files:
    - test-file.txt
  commands:
    - aspell list < test-file.txt

about:
  home: ftp://ftp.gnu.org/gnu/aspell/dict/0index.html
  license: "Various (see Copyright file from the aspell6-en source)"
  summary: "An (American, British, and Canadian) English dictionary for aspell."
