package:
  name: pyqt5
  version: 5.9

source:
  fn:   PyQt5_gpl-5.9.tar.gz 
  url:  https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.9/PyQt5_gpl-5.9.tar.gz
  sha1: 8920e4094470ff93f79e257c37c46f5cd0bff7ab                                        
  
requirements:
  build:
    - python
    - qt5     >=5.6.0
    - sip     >=4.18
    - gcc                 [linux]
    - numpy 1.11.1

  run:
    - python
    - qt5     >=5.6.0
    - sip     >=4.18
    - libgcc              [linux]
    - numpy 1.11.1

test:
  imports:
    - PyQt5.QtCore

about:
  home: http://www.riverbankcomputing.co.uk/software/pyqt
  license: GPL

