# This is an example of a meta package

package:
  name: test-meta
  version: 1.0

build:
  has_prefix_files:
    - test-has-prefix

requirements:
  run:
    - python
    - pycosat
    - bsdiff4
    - nose
