package:
  name: hunspell
  version: 1.3.2

source:
  fn: hunspell-1.3.2.tar.gz
  url: http://downloads.sourceforge.net/hunspell/hunspell-1.3.2.tar.gz
  sha1: 902c76d2b55a22610e2227abc4fd26cbe606a51c
  md5: 3121aaf3e13e5d88dfff13fb4a5f1ab8

build:
  number: 1

  has_prefix_files:
    - bin/hunspell

requirements:
  build:
    - readline

  run:
    - readline

test:
  commands:
    - hunspell --help

about:
  home: http://hunspell.sourceforge.net/
  summary: Spell checker
  license: MPL 1.1/GPL 2.0/LGPL 2.1
